export const CASE_GET_PRODUCTS = "GET_PRODUCTS";
export const CASE_GET_ONE_PRODUCT = "GET_ONE_PRODUCT";

export const CASE_GET_BRANDS = "GET_BRANDS";

export const CASE_GET_JEWERLY = "GET_JEWERLY";
export const CASE_GET_ONE_JEWERLY = "GET_ONE_JEWERLY";
